buildah_version: 100:1.22.3-2
podman_version:  100:3.4.2-4

spark_install_dir: /opt/spark/
spark_dowanload: /tmp/spark_dowanload/
spark_file: spark-3.3.2-bin-hadoop3-scala2.13
spark_file_ext: tgz
spark_file_url: https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3-scala2.13.tgz

spark_worker_memory: 8gb
spark_worker_cores: 3

hadoop_aws: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar
aws_java_sdk_bundle:  https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.99/aws-java-sdk-bundle-1.12.99.jar 
iceberg_spark_runtime: https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.13/1.1.0/iceberg-spark-runtime-3.3_2.13-1.1.0.jar 

postgresql_version: 12
