buildah_version: 100:1.22.3-2
podman_version:  100:3.4.2-4

spark_install_dir: /opt/spark/
spark_dowanload: /tmp/spark_dowanload/
spark_file: spark-3.3.2-bin-hadoop3-scala2.13
spark_file_ext: tgz
spark_file_url: https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3-scala2.13.tgz

spark_worker_memory: 8gb
spark_worker_cores: 3
