
####################   JDK ##########################
java_jdk: openjdk-17-jdk 
#$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"
# There may be better way to find JAVA_HOME
java_home: /usr/lib/jvm/java-1.17.0-openjdk-amd64
jceks_provider: jceks://file/usr/lib/java/secret.jceks
tmpfs_dir: /mnt/tmpfs/
tmpfs_size: 1M
passphrase: "ip route | sha1sum | cut -f 1 -d ' '"
application_group: application


######################## podman #########################
buildah_version: 100:1.22.3-2
podman_version:  100:3.4.2-4


############################## hadoop ##################### 

hadoop_user: hadoop
hadoop_home: /opt/hadoop
hadoop_version: 3.2.0
hadoop_url: https://archive.apache.org/dist/hadoop/core/hadoop-3.2.0/hadoop-3.2.0.tar.gz
hadoop_file_name: hadoop-3.2.0
hadoop_install_dir: /opt/hadoop


################### Spark #################
spark_home: /opt/spark/
spark_user: spark

spark_file_url: https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3-scala2.13.tgz
spark_file_name: spark-3.3.2-bin-hadoop3-scala2.13

spark_worker_memory: 8gb                     ##  adjust it
spark_worker_cores: 3                        ##  adjust it


spark_history_location: s3a://spark/logs


hadoop_aws_url: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar
hadoop_aws_file_name: hadoop-aws-3.3.2.jar
aws_java_sdk_bundle_url: https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.99/aws-java-sdk-bundle-1.12.99.jar 
aws_java_sdk_bundle_file_name: aws-java-sdk-bundle-1.12.99.jar 
iceberg_spark_runtime_url: https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.13/1.1.0/iceberg-spark-runtime-3.3_2.13-1.1.0.jar 
iceberg_spark_runtime_file_name: iceberg-spark-runtime-3.3_2.13-1.1.0.jar 

#####################   Postgresql   ##################
postgresql_version: 12
hive_db_name: hive
airflow_db_name: airflow
db_user: postgres                            ## pass from env 
db_password: postgres                        ## pass from env  
postgresql_connector_url: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.19/postgresql-42.2.19.jar
postgresql_connector_file_name: postgresql-42.2.19.jar


######################  minio ##############
minio_root_user: minioadmin
minio_root_password: minioadmin
minio_url: https://dl.min.io/server/minio/release/linux-amd64/minio
minio_cli_url: https://dl.min.io/client/mc/release/linux-amd64/mc
minio_file_name: minio

minio_dir: /opt/minio

minio_user: minio-user
fs_s3a_endpoint: http://127.0.0.1:9000
fs_s3a_access_key: minioadmin                 ##  pass from env
fs_s3a_secret_key: minioadmin                 ##  pass from env
metastore_warehouse_dir: s3a://warehouse/
##javax_jdo_option_ConnectionURL: jdbc:postgresql://:5432/hive

####################### hive metastore ##################
hive_user: hive
hive_metastore_url: https://archive.apache.org/dist/hive/hive-standalone-metastore-3.0.0/hive-standalone-metastore-3.0.0-bin.tar.gz
hive_metastore_url_file_name: hive-standalone-metastore-3.0.0-bin.tar.gz
hive_metastore_file_name: apache-hive-metastore-3.0.0-bin
hive_metastore_home: /opt/apache-hive-metastore


######################### jupyterhub ##############
jupyterhub_user: jupyterhub


######################### Trino #####################
trino_user: trino
trino_url: https://repo1.maven.org/maven2/io/trino/trino-server/410/trino-server-410.tar.gz
trino_file_name: trino-server-410
trino_home: /opt/trino
trino_jvm_mx: Xmx1G                           ##  adjust it
trino_data_dir: /var/trino/data
trino_port: 7080


######################### airflow #####################
airflow_user: airflow


######################### superset  #####################
superset_user: superset


######################### keycloak  #####################
keycloak_user:  keycloak

