---
- name: cleanup
  shell: '{{ item }}'
  loop:
      - systemctl stop  minio.service  
      - systemctl stop  keycloak 
      - systemctl stop  zookeeper  
      - systemctl stop  jupyter 
      - systemctl stop  trino 
      - systemctl stop  airflow 
      - systemctl stop   spark-master
      - systemctl stop   spark-worker-1
      - systemctl stop   spark-worker-3
      - rm -f /etc/systemd/system/minio.service       
      - rm -f /etc/systemd/system/keycloak.service       
      - rm -f /etc/systemd/system/spark*.service       
      - rm -f /etc/systemd/system/jupyter.service       
      - rm -f /etc/systemd/system/trino.service       
      - rm -f /etc/systemd/system/airflow.service       
      - 'apt remove postgresql-{{ postgresql_version }} -y'  
      - 'apt remove python3-pip -y' 
      - 'apt remove python3-psycopg2 -y' 
      - 'apt remove {{ java_jdk }} -y' 
      - 'systemctl daemon-reload'
      - 'rm -rf /opt/*'  
      - 'rm -rf /etc/default/minio'  
      - 'rm -rf /usr/lib/java/secret.jceks'  
      - 'rm -rf /usr/lib/java/.secret.jceks.crc'  
      - 'rm -rf {{ cert_dir }}'
      - 'rm -rf {{ lockbox_dir }}'
      - 'rm -rf {{ minio_home }}/.minio'
      - 'rm -rf /usr/local/share/ca-certificates/{{ ca_cert_file_name }}'  
      - '/usr/sbin/update-ca-certificates'  
      - umount /dev/sdb /dev/sdc /dev/sdd /dev/sde
      - wipefs -a /dev/sdb /dev/sdc /dev/sdd /dev/sde
  ignore_errors: True      
