---

- name: Check that the spark_install_dir exists
  stat:
      path: '{{ spark_home }}'
  register: stat_result
 
- name : extract spark zip
  unarchive:
     src: "http://{{ groups['repo'][0] }}/download/{{ spark_file_name }}.tgz"
     dest: /opt
     remote_src: true
     owner: '{{ spark_user }}'
     group: '{{ application_group }}'
  when: not stat_result.stat.exists  


- name: create soft link to /opt/spark   
  file:
     src: '/opt/{{ spark_file_name }}'
     dest: '/opt/spark'
     state: link
     owner: '{{ spark_user }}'
     group: '{{ application_group }}'
  when: not stat_result.stat.exists  

- name: get extra jar files 
  get_url:
     url: '{{ item }}'
     dest: '{{ spark_home }}/jars'
     owner: '{{ spark_user }}'
     group: '{{ application_group }}'
  loop:
     - "http://{{ groups['repo'][0] }}/download/{{ hadoop_aws_file_name }}" 
     - "http://{{ groups['repo'][0] }}/download/{{ aws_java_sdk_bundle_file_name }}" 
     - "http://{{ groups['repo'][0] }}/download/{{ iceberg_spark_runtime_file_name }}" 

