---

- name: sleep for 15 sec
  shell: sleep 15   

- name: Create databases
  shell:  'export PGPASSWORD={{ db_password }};/usr/bin/psql -h 127.0.0.1 -p {{ partoni_haproxy_port  }}  -U {{ db_user }} -c "CREATE DATABASE {{ item }}"' 
  loop: 
     - '{{ keycloak_db_name }}'
     - '{{ airflow_db_name }}'
     - '{{ superset_db_name }}' 
     - '{{ hive_db_name }}'  
     - '{{ iceberg_db_name }}'  
     - '{{ airbyte }}'  
  when: >
     inventory_hostname in groups['patroni']
     and  groups['patroni'].index(inventory_hostname) == 0 
  ignore_errors: yes    
    
