- name: install postgresql
  apt:
     name: ['postgresql-{{ postgresql_version }}' , 'python3-pip', 'python3-psycopg2']
     update_cache: yes
  loop:

- name: Stop postgresql
  systemd:
     name: postgresql
     state: stopped
     enabled: false
          
- name: install  patroni; 
  pip:
    name: '{{ item }}'
  loop:
    - psycopg2-binary
    - patroni[zookeeper]     

- name: create {{ patroni_data_dir }}  
  file:
     path: '{{ patroni_data_dir }}'     
     state: directory
     owner: '{{ db_user }}'
     group: '{{ application_group }}'
     mode: 0750

- name: create {{ patroni_home }}  
  file:
     path: '{{ patroni_home }}'     
     state: directory
     owner: '{{ db_user }}'
     group: '{{ application_group }}'

- name: copy patroni config file
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'patroni-node.yaml.j2', dest: '{{ patroni_home }}/patroni-node.yaml'  }
     - { src: 'patroni.service.j2', dest: '/etc/systemd/system/patroni.service'  }
  notify:
     -  restart patroni     

