- name: create {{ patroni_home }}  
  file:
     path: '{{ patroni_home }}'     
     state: directory
     owner: '{{ db_user }}'
     group: '{{ application_group }}'

- name: copy patroni config file
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'patroni-node.yaml.j2', dest: '{{ patroni_home }}/patroni-node.yaml'  }
     - { src: 'patroni.service.j2', dest: '/etc/systemd/system/patroni.service'  }
  notify:
     -  restart patroni     

- name: Reload service files
  systemd:
    daemon_reload: true       
- name: flush the handeler       
  meta: flush_handlers
