- name: Check that the python link exists
  stat:
      path: '/usr/bin/python'
  register: python_stat_result

- name: create soft link to /usr/bin/python
  file:
    src: '/usr/bin/python3'
    dest: '/usr/bin/python'
    state: link

- name: Install python3-pip
  apt:
    name: python3-pip
    update_cache: yes

- name: Install jre
  apt:
    name: '{{ java_jdk }}'
    update_cache: yes

- name: Check that the hadoop home exists
  stat:
      path: '{{ hadoop_home }}'
  register: hadoop_stat_result

- name : extract hadoop  zip
  unarchive:
     src: "http://{{ groups['repo'][0] }}/download/{{ hadoop_file_name }}.tar.gz"
     dest: /opt
     remote_src: true
     owner: '{{ hadoop_user }}'
     group: '{{ application_group }}'
  when: not hadoop_stat_result.stat.exists

- name: create soft link to /opt/hadoop
  file:
    src: '/opt/{{ hadoop_file_name }}'
    dest: '{{ hadoop_home }}'
    state: link
    owner: '{{ hadoop_user }}'
    group: '{{ application_group }}'
