---

- name: create group application
  group:
    name: '{{ application_group }}'
    state: present

- name: create tmpfs mount directory
  file:
     path: '{{ tmpfs_dir }}'
     state: directory 

- name: create  fstab entry 
  lineinfile: 
     dest: /etc/fstab
     line: tmpfs  /mnt/tmpfs  tmpfs   size={{ tmpfs_size }},mode=0777  0  0

- name: create tmpfs mount point  
  command: mount -a 

- name: create tmpfs mount directory
  file:
     path: '{{ tmpfs_dir }}'
     state: directory 
     mode: '0770'
     group: '{{ application_group }}'

- name: Install jre
  apt:
    name: '{{ java_jdk }}'
    update_cache: yes

- name: Create user hadoop
  user:
    name: '{{ hadoop_user }}'
    group: '{{ application_group }}'
    shell: /bin/bash

- name: Create user minio-user
  user:
    name: '{{ minio_user }}'
    group: '{{ application_group }}'
    shell: /bin/bash  

- name: Create user spark
  user:
    name: '{{ spark_user }}'
    group: '{{ application_group }}'
    shell: /bin/bash

- name: Create user jupyterhub_user
  user:
    name: '{{ jupyterhub_user }}'
    group: '{{ application_group }}'
    shell: /bin/bash

- name: Create user hive
  user:
    name: '{{ hive_user }}'
    group: '{{ application_group }}'
    shell: /bin/bash



- name: Check that the hadoop home exists
  stat:
      path: '{{ hadoop_home }}'
  register: hadoop_stat_result  

- name : extract hadoop  zip
  unarchive:
     src: "http://{{ groups['repo'][0] }}/download/{{ hadoop_file_name }}.tar.gz"
     dest: /opt
     remote_src: true
     owner: '{{ hadoop_user }}'
     group: '{{ application_group }}'
  when: not hadoop_stat_result.stat.exists

- name: create soft link to /opt/hadoop
  file:
    src: '/opt/{{ hadoop_file_name }}'
    dest: '{{ hadoop_home }}'
    state: link
    owner: '{{ hadoop_user }}'
    group: '{{ application_group }}'


- name:  create  jceks password
  shell: 'export JAVA_HOME={{ java_home }}; /opt/hadoop/bin/hadoop credential create  {{ item }}' 
  loop:
       - 'javax.jdo.option.ConnectionPassword -value {{ db_password }} -provider {{ jceks_provider }}'
       - 'fs.s3a.access.key -value {{ fs_s3a_access_key }} -provider {{ jceks_provider }}'
       - 'fs.s3a.secret.key -value {{ fs_s3a_secret_key }} -provider {{ jceks_provider }}'
  ignore_errors: yes       
         
- name: adjust secret.jceks
  file:
     path: /usr/lib/java/secret.jceks
     group: '{{ application_group }}'
     mode: '0640'
     
