---
- name: create group minio-user
  group:
    name: minio-user
    state: present

- name: Create user minio-user
  user:
    name: minio-user
    group: minio-user
    shell: /bin/bash

- name: Create mount point dit
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
  with_items:
    - { path: '/mnt/disk1', owner: 'minio-user'}
    - { path: '/mnt/disk2', owner: 'minio-user'}
    - { path: '/mnt/disk3', owner: 'minio-user'}
    - { path: '/mnt/disk4', owner: 'minio-user'}

- name: Create a xfs filesystem on /dev/sd*
  command: mkfs.xfs "{{ item.path }}"  -L "{{ item.label }}"
  with_items:
    - { path: '/dev/sdb', label: 'DISK1'}
    - { path: '/dev/sdc', label: 'DISK2'}
    - { path: '/dev/sdd', label: 'DISK3'}
    - { path: '/dev/sde', label: 'DISK4'}
  ignore_errors: true         

- name: Mount up device by label
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: present    
  with_items:
    - { path: '/mnt/disk1', src: 'LABEL=DISK1'}
    - { path: '/mnt/disk2', src: 'LABEL=DISK2'}
    - { path: '/mnt/disk3', src: 'LABEL=DISK3'}
    - { path: '/mnt/disk4', src: 'LABEL=DISK4'}
  ignore_errors: true         

- name: mount all the disks
  command: mount -a
