- name: install nginx
  apt:
     name: nginx      
  notify: restart nginx

- name: copy  spark-master.service
  template: src='static-file-server.conf.j2' dest='/etc/nginx/conf.d/static-file-server.conf'
  notify: restart nginx

- name: create a java dir
  file:
     path: /var/data/download     
     state: directory
     
- name : download  hadoop  zip
  get_url:
     url: '{{ item }}'
     dest: /var/data/download
  loop:
     - '{{ hadoop_url }}'      
     - '{{ hadoop_aws_url }}'      
     - '{{ aws_java_sdk_bundle_url }}'      
     - '{{ iceberg_spark_runtime_url }}'      
     - '{{ hive_metastore_url }}'      
     - '{{ postgresql_connector_url }}'
     - '{{ minio_url }}'
     - '{{ spark_file_url }}'
