- name:  create  jceks password
  shell: 'export JAVA_HOME={{ java_home }}; /opt/hadoop/bin/hadoop credential create  {{ item }}'
  loop:
       - 'javax.jdo.option.ConnectionUserName -value {{ db_user }} -provider {{ jceks_provider }}'
       - 'javax.jdo.option.ConnectionPassword -value {{ db_password }} -provider {{ jceks_provider }}'
       - 'fs.s3a.access.key -value {{ fs_s3a_access_key }} -provider {{ jceks_provider }}'
       - 'fs.s3a.secret.key -value {{ fs_s3a_secret_key }} -provider {{ jceks_provider }}'
  ignore_errors: yes


- name: adjust secret.jceks
  file:
     path: '{{ item }}'
     group: '{{ application_group }}'
     mode: '0640'
  loop:
     - /usr/lib/java/secret.jceks
     - /usr/lib/java/.secret.jceks.crc

- name: create  {{ lockbox_dir }}     
  file:
      path: '{{ lockbox_dir }}'   
      state:  directory
      group: '{{ application_group }}'

- name: copy lockbox files 
  template: src='{{ item.src }}' dest='{{ item.dest }}'  group='{{ application_group }}' mode=0650
  loop:
     - { src: 'decrypt_lockbox.sh.j2', dest: '{{ lockbox_dir }}/decrypt_lockbox.sh' }       
     - { src: 'encrypt_lockbox.sh.j2', dest: '{{ lockbox_dir }}/encrypt_lockbox.sh' }       
     - { src: '{{ lockbox_env }}.j2', dest: '{{ tmpfs_dir }}/{{ lockbox_env }}' }

- name: encrypt {{ lockbox_env }}    
  shell: '{{ lockbox_dir }}/encrypt_lockbox.sh'

- name: install passlib
  pip:
      name: passlib     

- name: create  {{ trino_password_dir }}     
  file:
      path: '{{ trino_password_dir }}'   
      state:  directory
      group: '{{ application_group }}'

- name: Add a user to a password file for trino
  htpasswd:
    path: '{{ trino_password_file }}'
    name: '{{ trino_user }}'
    password: '{{ trino_password }}'
    group: '{{ application_group }}'
    mode: 0640  
