scope: patroni
namespace: /service/
name: postgresql0

restapi:
    listen: node-2:8008
    connect_address: node-2:8008

bootstrap:
    dcs:
       ttl: 30
       loop_wait: 10
       retry_timeout: 10
       maximum_lag_on_failover: 1048576
       postgresql:
           use_pg_rewind: true

    postgresql:
      use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication all all md5
    - host all all all md5

zookeeper:
  hosts: 
    - node-1:2181
    - node-2:2181
    - node-3:2181
  use_ssl: false      

postgresql:
    listen: node-2:5432
    connect_address: node-2:5432    
    data_dir: /tmp/patroni
    pgpass: /tmp/pgpass
    parameters:
        unix_socket_directories: '.'
    authentication:
       replication:
           username: replicator
           password: password
       superuser:
           username: postgres
           password: password    

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
