---

- name: install libs
  apt: 
    name: [python3-virtualenv ,libldap2-dev,libffi-dev , libssl-dev , libsasl2-dev, libpq-dev]

- name: create  {{ superset_home }} 
  file: 
     path: '{{  superset_home }}' 
     state: directory
     owner: '{{ superset_user }}'
     group: '{{ application_group }}'

- name: create  {{ superset_home }}/pythonpath 
  file: 
     path: '{{  superset_home }}/pythonpath' 
     state: directory
     owner: '{{ superset_user }}'
     group: '{{ application_group }}'

- name: copy  superset files
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'requirements.txt.j2', dest: '{{  superset_home }}/requirements.txt'  }
     - { src: 'superset_config.py.j2', dest: '{{  superset_home }}/pythonpath/superset_config.py'  }

- name: install requirement
  pip:
     virtualenv:  '{{ superset_home }}/venv'   
     requirements: '{{ superset_home }}/requirements.txt' 
