---

- name: Create /etc/jupyterhub
  file: 
     path:  /etc/jupyterhub
     state: directory

- name: check for nodejs
  stat: 
     path: /usr/bin/node 
  register: stat_result   

- name: install nodejs part 1
  get_url:
    url:  https://deb.nodesource.com/setup_19.x
    dest: /tmp/
  when: not stat_result.stat.exists  

- name: install nodejs part 2
  shell: bash /tmp/setup_19.x
  when: not stat_result.stat.exists

- name: Install nodeja and python3-pip 
  apt:
    name: '{{ item }}'
    update_cache: yes
  loop:
    - nodejs
    - python3-pip      

- name: install jupyterhub and notebook
  pip: 
    name: '{{ item }}'
  loop:
    - jupyterhub      
    - notebook      
    - pyspark
    - findspark
    - numpy 
    - pandas
    - plotly 
    - seaborn 
    - matplotlib   
    - pyarrow  
    - scikit-learn 
    - scikit-image
    - pymc
    - statsmodels  
    - s3cmd
    - ipython-sql
    - sqlalchemy
    - sparksql-magic  
    - sqlalchemy-trino
    - clickhouse-driver
    - clickhouse-sqlalchemy
    - tensorflow  

- name: install configurable-http-proxy
  npm:
    name: configurable-http-proxy      
    global: yes

- name: copy  service and config file
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'jupyterhub.service.j2', dest: '/etc/systemd/system/jupyterhub.service'  }      
     - { src: 'jupyterhub_config_simple.py.j2', dest: '/etc/jupyterhub/jupyterhub_config_simple.py'  }      
     - { src: 'jupyterhub_config_keycloak.py.j2', dest: '/etc/jupyterhub/jupyterhub_config_keycloak.py'  }      
  notify: restart jupyterhub 


#- name: Reload jupyterhub.service
#  ansible.builtin.systemd:
#    name: jupyterhub.service
#    state: reloaded  

