---

- name: Create /etc/jupyterhub
  file: 
     path:  /etc/jupyterhub
     state: directory

- name: Create {{ jupyterhub_home }}
  file: 
     path:  '{{ jupyterhub_home }}'
     state: directory

- name: check for nodejs
  stat: 
     path: /usr/bin/node 
  register: stat_result   


- name: install nodejs part 1
  get_url:
    url:  https://deb.nodesource.com/setup_19.x
    dest: /tmp/
  when: not stat_result.stat.exists  

- name: install nodejs part 2
  shell: bash /tmp/setup_19.x
  when: not stat_result.stat.exists

- name: Install nodeja and python3-pip 
  apt:
    name: '{{ item }}'
    update_cache: yes
  loop:
    - nodejs
    - python3-pip      

      
- name: install jupyterhub and notebook
  pip: 
    name: '{{ item }}'
  loop:
    - jupyterhub==3.1      
    - JupyterLab==3.6.3
    - oauthenticator
    #- pyspark
    - plotly==3.7.1 
    - seaborn==0.12.2 
    - matplotlib== 3.7.1  
    - numpy==1.23.0 
    - pandas==2.0.1
    - pyarrow==11.0.0 
    - scikit-learn==1.2.2 
    - scikit-image==0.20.0
    - pymc==5.3.0
    - statsmodels==0.13.5  
    - s3cmd==2.3.0
    - ipython-sql==0.5.0
    - sqlalchemy==1.4.47
    - sparksql-magic==0.0.3  
    - sqlalchemy-trino==0.5.0
    #- clickhouse-driver
    #- clickhouse-sqlalchemy
    - tensorflow==2.12.0  

- name: install configurable-http-proxy
  npm:
    name: configurable-http-proxy      
    global: yes

- name: copy  service and config file
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode=0750 group='{{ application_group }}'
  loop:
     - { src: 'jupyterhub.service.j2', dest: '/etc/systemd/system/jupyterhub.service'  }      
     - { src: 'jupyterhub_config_simple.py.j2', dest: '/etc/jupyterhub/jupyterhub_config_simple.py'  }      
  notify: restart jupyterhub 

- name: Reload service files
  systemd:
    daemon_reload: true  

