---

- name: install postgresql
  apt:
     name: postgresql-{{ postgresql_version }}      
 
- name: Update postgresql.conf
  lineinfile:
     dest:  /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
     line: "listen_addresses = '*'"
  notify: restart postgresql.service

      
- name: Update bashrc for PythonBrew for foo user
  lineinfile:
     dest:  /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf 
     line: "host    replication     all             0.0.0.0/0            md5"
  notify: restart postgresql.service
