- name: install postgresql
  apt:
     name: ['postgresql-{{ postgresql_version }}' , 'python3-pip', 'python3-psycopg2']
     update_cache: yes

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
     - postgresql

- name: "Create db user"
  postgresql_user:
     state: present
     name: "{{ db_user }}"
     password: "{{ db_password }}"
  become: yes
  become_user: "{{ db_user }}"

#### create databases
- name: "Create hive database"
  postgresql_db:
     state: present
     name: "{{ hive_db_name }}"
  become: yes
  become_user: "{{ db_user }}"

- name: "Create  {{ keycloak_db_name }} database"
  postgresql_db:
     state: present
     name: "{{ keycloak_db_name }}"
  become: yes
  become_user: "{{ db_user }}"

- name: "Create  {{ airflow_db_name }} database"
  postgresql_db:
     state: present
     name: "{{ airflow_db_name }}"
  become: yes
  become_user: "{{ db_user }}"


- name: "Create  {{ superset_db_name }} database"
  postgresql_db:
     state: present
     name: "{{ superset_db_name }}"
  become: yes
  become_user: "{{ db_user }}"


### Create db role
- name: "Grant db user access to app db"
  postgresql_privs:
     type: database
     database: "{{ hive_db_name }}"
     roles: "{{ db_user }}"
     grant_option: no
     privs: all
  become: yes
  become_user: "{{ db_user }}"

- name: "Grant db user access to app db"
  postgresql_privs:
     type: database
     database: "{{ keycloak_db_name }}"
     roles: "{{ db_user }}"
     grant_option: no
     privs: all
  become: yes
  become_user: "{{ db_user }}"

- name: "Grant db user access to app db"
  postgresql_privs:
     type: database
     database: "{{ airflow_db_name }}"
     roles: "{{ db_user }}"
     grant_option: no
     privs: all
  become: yes
  become_user: "{{ db_user }}"

- name: "Grant db user access to app db"
  postgresql_privs:
     type: database
     database: "{{ superset_db_name }}"
     roles: "{{ db_user }}"
     grant_option: no
     privs: all
  become: yes
  become_user: "{{ db_user }}"


- name: Update pg_hba.conf
  lineinfile:
     dest:  /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
     line: "host    all     all             0.0.0.0/0            md5"
  notify: restart postgresql.service

- name: Update postgresql.conf
  lineinfile:
     dest:  /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
     line: "listen_addresses = '*'"
  notify: restart postgresql.service

- name: Create airflow__extra_conf table
  postgresql_table:
    name: airflow__extra_conf
    columns:
    - conf_name  VARCHAR (255) PRIMARY KEY
    - conf_value VARCHAR (255) NOT NULL   
  become_user: "{{ db_user }}"

