- name: download the minio binary
  get_url:
    url: "http://{{ groups['repo'][0] }}/download/minio" 
    dest: /usr/local/bin/minio 
    mode: '0555'
  notify: restart minio     
    
- name: 
  template:
     src: minio.j2
     dest: /etc/default/minio
  notify: restart minio     

- name: 
  template: 
     src: minio.service.j2
     dest: /etc/systemd/system/minio.service
  notify: restart minio     

- name: 
  template: 
     src: minio.env.j2
     dest: '{{ tmpfs_dir }}/minio.env'
  notify: restart minio     
