---

- name: create {{ minio_dir }}
  file:    
     path: '{{ minio_dir }}'
     state: directory
     owner: '{{ minio_user }}'
     group: '{{ application_group }}'


- name: download the minio binary
  get_url:
     url: "http://{{ groups['repo'][0] }}/download/minio" 
     dest: /usr/local/bin/minio 
     mode: '0555'

  notify: restart minio     


- name: copy  minio env files
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode='{{ item.mode }}' owner='{{ minio_user }}' group='{{ application_group }}'
  loop:
     - { src: 'minio.j2', dest: '/etc/default/minio', mode: 0644 }
     - { src: 'minio.service.j2', dest: '/etc/systemd/system/minio.service', mode: 644}
  notify: restart minio     
    
